### ISSUE TITLE
Settings Tab aufrufen führt zu Fehler

### ISSUE THREAD

**Issue by yvseiler** [ilub-unibe-ch/OpenCast#2]
**Describe the bug**
Bei diesem Opencast Serie führt ein Klick auf "Einstellungen" Tab zu einem Fehler: https://ilias.unibe.ch/goto_ilias3_unibe_xoct_3146822.html

**Entschuldigung, es ist ein Fehler aufgetreten. Eine Logdatei wurde erzeugt, die über den Error Code „u1m51_9361“ identifiziert werden kann.**
2.9.2024 17:55 Uhr

Andere Opencast Serie funktionieren und ergeben keinen Fehler, z.B. https://ilias.unibe.ch/goto_ilias3_unibe_xoct_1784541.html

**To Reproduce**
1. Öffne Opencast Serie.
2. Klicke auf "Einstellungen"

**Expected behavior**
Formular "Einstellungen" wird angezeigt.

**Environment (please complete the following information):**
 - ILIAS version: ILIAS (v8.14 2024-08-13)
 - Browser: Chrome auf macOS

**Comment by yvseiler** [comment]
Die fehlerhafte Opencast Serie ist eine Verknüpfung von der Serie hier im Kurs: https://ilias.unibe.ch/goto_ilias3_unibe_crs_1997460.html (scrolle zur Mitte zum Titel "2. Objekte wie LiveVoting und Video ins neue Semester kopieren"). Wenn man bei dieser Serie auf Aktionen und "Info" klickt, erhält man ebenfalls eine Fehlermeldung: Entschuldigung, es ist ein Fehler aufgetreten. Eine Logdatei wurde erzeugt, die über den Error Code „u1m51_4936“ identifiziert werden kann.

Sie gehört auch zu dem Thoraxtrauma-Ordner, bei dem wir heute Probleme mit dem Öffnen hatten (siehe Issue https://github.com/ilub-unibe-ch/ILIAS/issues/90), wurde aber erst hinzugefügt, nachdem Issue 90 behoben worden ist.

**Comment by okaufman** [comment]
gefixt
