### ISSUE TITLE
Sorting by the column "Date" is done alphabetically instead of chronologically

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/OpenCast#4]
**Describe the bug**
Sorting by the colum "Date" is done alphabetically instead of chronologically

**Expected behavior**
Sorting should be done chronologically

**Screenshots**
Bug:
<img width="437" alt="grafik" src="https://github.com/user-attachments/assets/d237c32d-bac6-4cc9-a6d5-e666cacf2871">

**Comment by Amstutz** [comment]
resolved
