### ISSUE TITLE
Konfig PaellaPlayer anpassen (Pull-Request auf ilias.unibe.ch aufspielen)

### ISSUE THREAD

**Issue by samuelinniger** [ilub-unibe-ch/OpenCast#7]
Lieber Timon,

Olivia ist nicht mehr dazu gekommen, diesen Pullrequest auf ILIAS Produktiv aufzuschalten.
Inhalt: Anpassung an der Konfiguration des integrierten "Paella Players". 
https://github.com/ilub-unibe-ch/OpenCast/pull/5

Sascha und ich haben die neue Konfig auf ilias-next getestet.

Merci fürs Aufschalten!

**Comment by Amstutz** [comment]
Published on ILIAS Next. Please test

**Comment by samuelinniger** [comment]
Das stimmt so alles auf ILIAS-Next, merci!
Kann bei nächster Gelegenheit auf ILIAS Produktiv augespielt werden, thx.

**Comment by samuelinniger** [comment]
Kann bei nächster Gelegenheit auf ILIAS Produktiv augespielt werden. Merci @okaufman!

**Comment by okaufman** [comment]
Ich habe die Änderung auf ilias-prod eingespielt.
